Vagrant.configure("2") do |config|

	$domain = "my.home"
	$etcd_name_prefix = "etcd-server"
	$docker_name_prefix = "docker-swarm"
	$k8s_name_prefix = "k8s"
	$k8s_srv_prefix = "master"
	$k8s_slv_prefix = "worker"
	# aws t2.micro instance
	$t2_micro_mem = 1024
	$t2_micro_cpu = 1
	# awm t2.medium instance
	$t2_medium_mem = 4096
	$t2_medium_cpu = 2
	# aws t2.nano instance
	$t2_nano_mem = 512
	$t2_nano_cpu = 1
	# aws t2.small instance
	$t2_nano_mem = 2048
	$t2_nano_cpu = 1
	# t2.small
	$k8s_srv_mem = 2048 				# RAM in Gb
	$k8s_srv_cpu = 2					# CPU count
	# 
	$k8s_slv_mem = 4096 				# RAM in Gb
	$k8s_slv_cpu = 2					# CPU count
	
	$k8s_master_begin_ip_range = 10
	$k8s_worker_begin_ip_range = 20
	$docker_swarm_begin_ip_range = 99
	$etcd_begin_ip_range = 50
	$private_net = "172.0.0."
	$vbox_img = "centos/7"

	#Run Kubernetes master server
    config.vm.define "#{$k8s_name_prefix}#{$k8s_srv_prefix}" do |master|
	    master.vm.box = "#{$vbox_img}"
	    master.vm.hostname = "#{$k8s_name_prefix}#{$k8s_srv_prefix}"
	    master.vm.network :private_network, ip: "#{$private_net}#{$k8s_master_begin_ip_range}"
		master.vm.network "forwarded_port", guest: 22, host: 10022
	    master.vm.provider :virtualbox do |vb|
	    	vb.customize [
	    		"modifyvm", :id,
	    		"--cpuexecutioncap", "60",
	    		"--memory", "#{$k8s_srv_mem}",
	    		"--cpus", "#{$k8s_srv_cpu}",
	    		"--audio", "none",
	    	]
	    end
    end

    # Run Kubernetes worker nodes
	(1..1).each do |i|
		config.vm.define "#{$k8s_name_prefix}#{$k8s_slv_prefix}#{i}" do |node|
			node.vm.box = "#{$vbox_img}"
			node.vm.hostname = "#{$k8s_name_prefix}#{$k8s_slv_prefix}#{i}"
			node.vm.network :private_network, ip: "#{$private_net}#{$k8s_worker_begin_ip_range+i}"
			node.vm.network "forwarded_port", guest: 22, host: 10023
			node.vm.provider :virtualbox do |vb|
				vb.customize [
					"modifyvm", :id,
					"--cpuexecutioncap", "60",
					"--memory", "#{$k8s_slv_mem}",
					"--cpus", "#{$k8s_slv_cpu}",
					"--audio", "none",
				]
			end
		end
	end	
end
